
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-rec-s25-14
owner: ucsb-cs156-s25
repo_name: proj-rec-s25-14
pull_requests: [{"author":{"id":"U_kgDOCM7wqA","is_bot":false,"login":"siddhimundhra1","name":""},"headRefName":"sm-hardcode","number":52,"title":"The list of hardcoded request types above is added into the Request Type table at startup (check for each one to see if is already there before loading it).","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-14/pull/52"},{"author":{"id":"U_kgDOB3D-ww","is_bot":false,"login":"chloeandersen-ucsb","name":""},"headRefName":"chloe-issue14","number":48,"title":"SUBISSUE: Professor can modify the status column on the Pending Requests Page","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-14/pull/48"},{"author":{"id":"U_kgDOB09Zlw","is_bot":false,"login":"ryanchoi07","name":""},"headRefName":"foreign-key-recommendationtype","number":45,"title":"Modified RecommendationRequest recommendationType to be a foreign key to RequestType","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-14/pull/45"},{"author":{"id":"U_kgDOB09Zlw","is_bot":false,"login":"ryanchoi07","name":""},"headRefName":"remove-role-student","number":44,"title":"remove all role_student","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-14/pull/44"},{"author":{"id":"MDQ6VXNlcjY1NDY4MjU1","is_bot":false,"login":"karenlyuan","name":"Karen Yuan"},"headRefName":"karen-student-role-default","number":43,"title":"all users given Student role by default already","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-14/pull/43"},{"author":{"id":"U_kgDOB3D-ww","is_bot":false,"login":"chloeandersen-ucsb","name":""},"headRefName":"chloe-issue23","number":41,"title":"SUBISSUE: Add Recommendation Requests Table to Professor Pending Request Page","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-14/pull/41"}]
