
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-rec-s25-14
owner: ucsb-cs156-s25
repo_name: proj-rec-s25-14
pull_requests: [{"author":{"id":"U_kgDOB3D-ww","is_bot":false,"login":"chloeandersen-ucsb","name":""},"headRefName":"chloe-issue19","number":33,"title":"FEATURE: Professor Pending Requests Page #19","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-14/pull/33"},{"author":{"id":"U_kgDOCM7wqA","is_bot":false,"login":"siddhimundhra1","name":""},"headRefName":"sm-format-dates","number":31,"title":"Changed frontend to parse the ISO formatted dates using substring and updated tests for Recommendation Request Table","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-14/pull/31"},{"author":{"id":"U_kgDOCM7wqA","is_bot":false,"login":"siddhimundhra1","name":""},"headRefName":"sm-ensure-student-default","number":30,"title":"Fixed Bug - Student should be true when new user logs in","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-14/pull/30"},{"author":{"id":"U_kgDOB3D-ww","is_bot":false,"login":"chloeandersen-ucsb","name":""},"headRefName":"chloe-issue1","number":29,"title":"BUG: Completion Date not stored in Recommendation Requests Table #1","url":"https://github.com/ucsb-cs156-s25/proj-rec-s25-14/pull/29"}]
